<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FileTools</AssemblyName>
    <RootNamespace>FileTools</RootNamespace>
    <Version>1.0.1.2</Version>
    <AssemblyVersion>1.0.1.2</AssemblyVersion>
    <FileVersion>1.0.1.2</FileVersion>
    <InformationalVersion>1.0.1.2</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\FileToolsIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Remove="Ui\MainForm.*.resx" />
    <Compile Update="Ui\MainForm.Designer.cs">
      <DependentUpon>MainForm.cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Resources\Strings.ko.resx">
      <DependentUpon>Strings.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="Ui\MainForm.resx">
      <DependentUpon>MainForm.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
</Project>
